# Generated by Django 6.0.3 on 2026-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date_at'), name='uniq_conv_rate_for_date')],
            },
        ),
        migrations.CreateModel(
            name='CustomConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'from_currency', 'to_currency', 'date_at'), name='uniq_custom_conv_rate_for_date')],
            },
        ),
        migrations.CreateModel(
            name='CustomCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'user_id'), name='uniq_custom_currency_for_user')],
            },
        ),
    ]
