# Generated by Django 6.0.3 on 2026-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversionrate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date_at'), name='uniq_conv_rate_for_date'),
        ),
    ]
