# Generated by Django 6.0.3 on 2026-04-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_conversionrate_uniq_conv_rate_for_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConversionRate',
            fields=[
                ('conversionrate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.conversionrate')),
                ('user_id', models.IntegerField()),
            ],
            bases=('api_app.conversionrate',),
        ),
        migrations.CreateModel(
            name='CustomCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('user_id', models.IntegerField()),
            ],
            options={
            },
        ),
    ]
