# Generated by Django 6.0.3 on 2026-04-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_customconversionrate_customcurrency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customcurrency',
            constraint=models.UniqueConstraint(fields=('code', 'user_id'), name='uniq_custom_currency_for_user'),
        ),
    ]
