# Generated by Django 6.0.3 on 2026-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_project_tag_alter_task_options_remove_task_is_done_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='uniq_task_title_in_project'),
        ),
    ]
